name: Build Check

permissions: write-all

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

jobs:
  lingmo:
    name: LingmoOS 2.0
    runs-on: ubuntu-latest
    container: ghcr.io/lingmoos-testing/lingmo:polaris
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Fix APT sources
        run: |
          rm -rfv /etc/apt/sources.list
          echo "deb https://packages.lingmo.org polaris main contrib non-free non-free-firmware" >> /etc/apt/sources.list
          echo "deb https://mirrors.bfsu.edu.cn/debian/ testing main contrib non-free non-free-firmware" >>  /etc/apt/sources.list

    - name: Update repository
      run: apt-get update -y

    - name: Install the basic dev packages
      run: apt-get install -y equivs curl git devscripts lintian build-essential automake autotools-dev cmake g++
    
    - name: Install build dependencies
      run: mk-build-deps -i -t "apt-get --yes" -r
    
    - name: Fix KF5
      run: mkdir -p /usr/include/KF5
    
    - name: Build Package
      run: |
        dpkg-buildpackage -b -uc -us -j$(nproc)
